name: Waka Readme
on:
  workflow_dispatch: # This line adds the manual "Run" button
  schedule:
    - cron: "0 0 * * *" # Runs automatically every day at midnight
jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: "->"
          TIME_RANGE: all_time 
          SHOW_TIME: true
